### ISSUE TITLE
pkgDir.sync is not a function in index.js

### ISSUE THREAD

**Issue by amaurypichat** [sindresorhus/import-local#15]
I got this error while executing npm run test. I recently upgrade all versions of node, next.js, react.js and jest and I didn't have this error before. The test checks the text inside a react component located in a jsx file. I didn't find anything about this error on the net.
![Capture](https://github.com/sindresorhus/import-local/assets/153305282/5336ae20-a0cd-4f68-b6a0-4063eac655ca)

```
"dependencies": {
    "@babel/plugin-syntax-jsx": "^7.24.1",
    "@babel/plugin-transform-react-jsx": "^7.23.4",
    "@babel/preset-react": "^7.24.1",
    "@next/font": "14.2.3",
    "@react-spring/three": "^9.7.3",
    "@react-three/cannon": "^6.6.0",
    "@react-three/drei": "^9.105.5",
    "@react-three/fiber": "^8.16.2",
    "@react-three/postprocessing": "^2.16.2",
    "@types/node": "20.12.7",
    "@types/react": "18.3.1",
    "@types/react-dom": "18.3.0",
    "autoprefixer": "^10.4.19",
    "babel-jest": "^29.7.0",
    "babel-plugin-glsl": "^1.0.0",
    "bootstrap": "^5.3.3",
    "eslint": "9.1.1",
    "eslint-config-next": "14.2.3",
    "framer-motion": "^11.1.7",
    "gl-react": "^5.2.0",
    "glsl-noise": "^0.0.0",
    "glslify": "^7.1.1",
    "gsap": "^3.12.5",
    "html-react-parser": "^5.1.10",
    "leva": "^0.9.35",
    "lodash": "^4.17.21",
    "next": "14.2.3",
    "next-absolute-url": "^1.2.2",
    "next-unused": "^0.0.6",
    "papaparse": "^5.4.1",
    "postcss": "^8.4.38",
    "react": "18.3.1",
    "react-device-detect": "^2.2.3",
    "react-dom": "18.3.1",
    "sass": "^1.75.0",
    "tailwindcss": "^3.4.3",
    "three": "^0.149.0",
    "three-stdlib": "^2.29.9",
    "typescript": "5.4.5",
    "zustand": "^4.5.2"
  },
"devDependencies": {
    "@babel/preset-env": "^7.24.4",
    "@testing-library/jest-dom": "^6.4.2",
    "@testing-library/react": "^15.0.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "purify-css": "^1.2.5"
  },
```

Does it really relies on your package ? Do you know what to do ?

**Comment by silenius** [comment]
same here:

```
                  /usr/local/www/sites/gbif-alert/node_modules/import-local/index.js:7
                        const globalDir = pkgDir.sync(path.dirname(filename));
                                                 ^
                  
                  TypeError: pkgDir.sync is not a function
                      at module.exports (/usr/local/www/sites/gbif-alert/node_modules/import-local/index.js:7:27)
                      at Object.<anonymous> (/usr/local/www/sites/gbif-alert/node_modules/webpack-cli/bin/cli.js:10:7)
                      at Module._compile (node:internal/modules/cjs/loader:1369:14)
                      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
                      at Module.load (node:internal/modules/cjs/loader:1206:32)
                      at Module._load (node:internal/modules/cjs/loader:1022:12)
                      at Module.require (node:internal/modules/cjs/loader:1231:19)
                      at require (node:internal/modules/helpers:179:18)
                      at runCli (/usr/local/www/sites/gbif-alert/node_modules/webpack/bin/webpack.js:90:3)
                      at Object.<anonymous> (/usr/local/www/sites/gbif-alert/node_modules/webpack/bin/webpack.js:188:2)
                  
                  Node.js v20.12.2

```

**Comment by beast-19** [comment]
I was facing the same issue; the problem was the mismatched version of the package. So I suggest you delete node_modules and package-lock.json, run "npm install" and try again. The issue will be resolve probably.
